### ISSUE TITLE
I need fexpect.api local. 

### ISSUE THREAD

**Issue by koba-ninkigumi** [JasperVanDenBosch/fexpect#1]
I need fexpect.api local.
Do you have plans?

**Comment by JasperVanDenBosch** [comment]
Hi Koba Ninkigumi,

Fexpect should work local as well. You can use 'localhost' as host, or do
you mean something else?

Cheers,

Jasper
jasper@ilogue.com

On 9 April 2012 18:41, koba-ninkigumi <
reply@reply.github.com

> wrote:
> 
> I need fexpect.api local.
> Do you have plans?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ilogue/fexpect/issues/1

## 

I'd love to see your attachment, but please use OpenDocument, not a
proprietary format like docx. It's an international standard, endorsed by
the EU, and implemented in many office suites, such as LibreOffice, and
commercial products from Oracle, Sun, IBM and Microsoft (from 2007).

**Comment by JasperVanDenBosch** [comment]
I see now, you mean local() ofcourse. This should be easy, I will implement it later today.

**Comment by JasperVanDenBosch** [comment]
Hi Koba Ninkigumi,

I have implemented local. Please let me know if it doesn't work as expected!

Thank you,

Jasper
