### ISSUE TITLE
executing local command, but it prompts "No hosts found. Please specify (single) host string for connection"

### ISSUE THREAD

**Issue by tly1980** [JasperVanDenBosch/fexpect#12]
Here is my code, 

``` python
from ilogue.fexpect import expect, expecting, local


@task
def test_expect():
    prompts = []
    prompts += expect('enter aes-256-cbc decryption password', 'abc')

    with expecting(prompts):
        local('echo "ENCRYPTED TEXT...." | openssl enc -d -aes-256-cbc -a')
```

however it gives me following error

```
No hosts found. Please specify (single) host string for connection:
```

This is supposed to be a local command. Why it is asking me the host config ?

**Comment by tly1980** [comment]
Fabric & fexpect version:
Fabric==1.7.0
fexpect==0.2.post7

**Comment by jladdjr** [comment]
Hi tly1980,

Thanks for touching base with the issue you mentioned. Let me dig into this
and see if I can find a fix for you - thanks!

Jim

**Comment by beaugunderson** [comment]
Also hitting this fabric==1.8.0 and fexpect==0.2.post7.

**Comment by gblaha** [comment]
Me too.  Would love for local() to not require a hostname.  Looks like the problem might be that local() calls wrapExpectations(), which calls fabric.api.put().  For a "local" fabric task, a simple local file operation -- rather than a fabric.api.put() call -- should do.

**Comment by JasperVanDenBosch** [comment]
I agree, but don't have the time to look into this now.. sorry.

**Comment by quietlyconfident** [comment]
The pull request I submitted (#18) fixes this issue.

**Comment by JasperVanDenBosch** [comment]
Thanks Erik! Looks good. 
Do most of you just clone from here or is there a lot of interest to update the pypi package?

**Comment by quietlyconfident** [comment]
Hi-

Thank you!  I can’t speak for anyone else, but I would use the pypi package if it were updated; it makes it simpler to automate installations.

-Erik

**Comment by JasperVanDenBosch** [comment]
Alright, fexpect-0.2.post17 is now on pypi.
