### ISSUE TITLE
Why is ilogue necessary?

### ISSUE THREAD

**Issue by jayd3e** [JasperVanDenBosch/fexpect#7]
Why not just use the namespace fexpect?  Not a huge deal, but I'm just curious why you have it organized this way.

**Comment by JasperVanDenBosch** [comment]
Hi Jayd3e, 

Thanks for your question. As I have several python packages (some only for internal use or still in early stages) in deployment it sometimes makes it easier to have all packages in one namespace package together, so it is just for my convenience.

Best, Jasper
